// Offline tests for the #247 prose-lint-on-write PostToolUse hook
// (.claude/hooks/lint-doc-prose.ts). All logic is in the exported pure
// shouldLint()/planLint()/resolveValeConfig(), so these run with no Vale, no
// spawn, no network. The acceptance criteria map directly onto shouldLint:
// editing a wiki/decisions/STATE file lints; generated + vendored paths do not.

import { describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { planLint, resolveValeConfig, shouldLint } from "../.claude/hooks/lint-doc-prose";

describe("shouldLint() — living-doc scope", () => {
  // The acceptance list: these MUST lint.
  test.each([
    "docs/STATE.md",
    "docs/decisions.md",
    "docs/milestones.md",
    "docs/wiki/engineering-lessons.md",
    "docs/wiki/team-structure.md",
    "README.md",
    "docs/superpowers/specs/2026-07-10-spacemolt-harness-design.md",
    // Absolute + Windows-slash paths (the payload's file_path is whatever the tool got).
    "E:\\projects\\spacemolt\\docs\\STATE.md",
    "/home/runner/spacemolt/docs/wiki/harness-parts.md",
  ])("lints living-doc prose: %s", (p) => {
    expect(shouldLint(p)).toBe(true);
  });

  // These MUST NOT lint.
  test.each([
    "docs/backlog.md", // generated by scripts/gen-backlog.py
    "docs/assets/diagram.md", // generated / asset tree
    "docs/game-reference/commands.md", // vendored game docs, not ours to restyle
    "docs/game-reference/README.md", // README under a vendored tree still skipped
    ".claude/wave-state.md", // generated, not under docs/
    "src/registry/actions.ts", // not markdown
    "docs/STATE.txt", // not markdown
    "package.json", // not markdown, not a doc
    "notes/scratch.md", // markdown but not a living-doc location
  ])("skips out-of-scope path: %s", (p) => {
    expect(shouldLint(p)).toBe(false);
  });

  test("empty / undefined path is out of scope, never a crash", () => {
    expect(shouldLint(undefined)).toBe(false);
    expect(shouldLint("")).toBe(false);
  });
});

describe("planLint() — graceful degradation", () => {
  const docsFile = "docs/STATE.md";

  test("out-of-scope skips before touching config or vale", () => {
    expect(planLint("docs/backlog.md", "/some/.vale.ini", "/usr/bin/vale")).toEqual({
      action: "skip",
      reason: "out-of-scope",
    });
  });

  test("missing config degrades to advisory skip, never blocks", () => {
    expect(planLint(docsFile, null, "/usr/bin/vale")).toEqual({
      action: "skip",
      reason: "no-config",
    });
  });

  test("missing vale binary degrades to advisory skip, never blocks", () => {
    expect(planLint(docsFile, "/some/.vale.ini", null)).toEqual({
      action: "skip",
      reason: "no-vale",
    });
  });

  test("in scope with config and vale present ⇒ run", () => {
    expect(planLint(docsFile, "/some/.vale.ini", "/usr/bin/vale")).toEqual({
      action: "run",
      config: "/some/.vale.ini",
    });
  });
});

describe("resolveValeConfig() — resolution order", () => {
  test("returns null when no candidate exists", () => {
    const empty = mkdtempSync(join(tmpdir(), "prose-noconfig-"));
    try {
      expect(resolveValeConfig({}, empty, empty)).toBeNull();
    } finally {
      rmSync(empty, { recursive: true, force: true });
    }
  });

  test("explicit PROSE_LINT_VALE_CONFIG wins over the filesystem fallbacks", () => {
    const dir = mkdtempSync(join(tmpdir(), "prose-envconfig-"));
    const cfg = join(dir, "custom.vale.ini");
    writeFileSync(cfg, "StylesPath = styles\n");
    try {
      expect(resolveValeConfig({ PROSE_LINT_VALE_CONFIG: cfg }, dir, dir)).toBe(cfg);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test("a set-but-nonexistent env override falls through, not returned blindly", () => {
    const empty = mkdtempSync(join(tmpdir(), "prose-badenv-"));
    try {
      expect(
        resolveValeConfig({ PROSE_LINT_VALE_CONFIG: join(empty, "nope.ini") }, empty, empty),
      ).toBeNull();
    } finally {
      rmSync(empty, { recursive: true, force: true });
    }
  });
});
