// PostToolUse hook (matcher: Write|Edit) — the #247 prose-lint-on-write gate.
//
// The Vale prose-lint kit (ai-tells + Cringely styles) fired at only two manual
// points: the /prose-lint skill on demand, and doc-steward charter step 8. PM and
// implementer edits to the living docs BETWEEN steward passes shipped unlinted —
// and the living docs are the operator's remote view, where AI-tell prose is the
// named complaint (#247). The trigger existed only as a machine-GLOBAL PostToolUse
// hook on the operator's settings.json, so a fresh clone, a teammate, or a CI run
// got nothing. This versions the TRIGGER in the repo so any Claude Code session in
// the checkout fires it; the STYLES engine stays the prose-lint skill's kit (the
// issue's own words: "running Vale with the existing styles via the prose-lint
// skill's engine"), which has its own SSOT (beautiful_prose skill + the Cringely
// style builder + `vale sync`) and must not be duplicated into the repo.
//
// WARN, never deny (matches the prose-lint skill's "advisory, not a gate"
// contract and the design sketch): findings surface as PostToolUse
// additionalContext the writing agent addresses or waves off in the PR body. A
// deny would block a STATE-freshness update on a style nit — wrong tradeoff for a
// handoff file.
//
// Scope (shouldLint): the CHANGED file only, and only living-doc prose — root
// README.md or anything under docs/ — MINUS generated files (docs/backlog.md,
// docs/assets/*) and the vendored game-reference docs (not ours to restyle). The
// project's own .claude/, node_modules, etc. are not under docs/ so the allowlist
// already excludes them.
//
// Degrade gracefully (planLint): the harness has ZERO new runtime dependencies —
// Vale is an external tool a clone or CI runner may not have, and the styles kit
// may be absent too. Missing config or missing `vale` binary ⇒ advisory skip with
// a one-line notice to stderr, exit 0. Never block a write on a missing binary.
//
// Config resolution (resolveValeConfig): an explicit PROSE_LINT_VALE_CONFIG env
// override first (CI-friendly), then a repo-vendored kit if a future PR adds one
// (.claude/tools/prose-lint/.vale.ini — absent today), then the machine-global kit
// the skill and the old global hook already use. Vale resolves the config's
// StylesPath relative to the config file, so pointing --config at the global
// .vale.ini finds its styles/ with no extra wiring.
//
// The decision logic lives in the exported pure shouldLint()/planLint() so
// `bun test test/lint-doc-prose.test.ts` exercises it offline — no Vale, no spawn,
// no network. The stdin/stdout contract and the real Vale run are the thin
// side-effecting main below.

import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

/** Generated or vendored paths under docs/ that are not ours to restyle. */
const SKIP_PATHS = [
  /(^|\/)docs\/backlog\.md$/i, // generated by scripts/gen-backlog.py
  /(^|\/)docs\/assets\//i, // generated / binary assets
  /(^|\/)docs\/game-reference\//i, // vendored game docs (verbatim upstream)
];

/**
 * Is `filePath` a living-doc prose file this hook should lint? Root README.md or
 * anything under docs/, ending .md/.markdown, that is not a generated or vendored
 * path. Accepts absolute or relative paths, any slash style.
 */
export function shouldLint(filePath: string | undefined): boolean {
  if (typeof filePath !== "string" || filePath === "") return false;
  const norm = filePath.replace(/\\/g, "/");

  if (!/\.(md|markdown)$/i.test(norm)) return false;

  // Living-doc allowlist: root README.md, or anything under a docs/ directory.
  const isReadme = /(^|\/)README\.md$/i.test(norm);
  const inDocs = /(^|\/)docs\//i.test(norm);
  if (!isReadme && !inDocs) return false;

  if (SKIP_PATHS.some((re) => re.test(norm))) return false;

  return true;
}

/**
 * Resolve the Vale config for the prose-lint kit, or null if none is reachable.
 * Order: explicit env override, repo-vendored kit (forward seam; absent today),
 * machine-global kit. `home` and `scriptDir` are injectable for tests.
 */
export function resolveValeConfig(
  env: Record<string, string | undefined> = process.env,
  home: string = homedir(),
  scriptDir: string = import.meta.dir,
): string | null {
  const candidates = [
    env.PROSE_LINT_VALE_CONFIG,
    join(scriptDir, "..", "tools", "prose-lint", ".vale.ini"),
    join(home, ".claude", "tools", "prose-lint", ".vale.ini"),
  ].filter((p): p is string => typeof p === "string" && p !== "");
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  return null;
}

export type LintPlan =
  | { action: "skip"; reason: "out-of-scope" | "no-config" | "no-vale" }
  | { action: "run"; config: string };

/**
 * Pure plan over the three inputs the side-effecting main gathers: the target
 * path, the resolved Vale config (or null), and the vale binary path (or null).
 * Out-of-scope is fully silent; a missing config or binary degrades to an
 * advisory skip the main reports in one line.
 */
export function planLint(
  filePath: string | undefined,
  config: string | null,
  valePath: string | null,
): LintPlan {
  if (!shouldLint(filePath)) return { action: "skip", reason: "out-of-scope" };
  if (!config) return { action: "skip", reason: "no-config" };
  if (!valePath) return { action: "skip", reason: "no-vale" };
  return { action: "run", config };
}

/** The advisory context wrapped around Vale's findings before it is injected. */
export function buildContext(file: string, findings: string): string {
  return [
    `Prose-lint (advisory) flagged AI-tells in the document just written: ${file}`,
    "",
    findings.trim(),
    "",
    "These are Vale findings, NOT a gate. Quoted text, code identifiers, and API",
    "names trigger false positives, so name those in the PR body rather than",
    '"fixing" them. If real tells remain, apply the beautiful_prose skill Edit mode',
    "to the flagged passages instead of hand-guessing.",
  ].join("\n");
}

if (import.meta.main) {
  try {
    const payload = JSON.parse(await Bun.stdin.text()) as {
      tool_input?: { file_path?: string };
    };
    const file = payload?.tool_input?.file_path;

    const config = resolveValeConfig();
    const valePath = Bun.which("vale");
    const plan = planLint(file, config, valePath);

    if (plan.action === "skip") {
      // Out-of-scope is silent by design. A missing engine gets one advisory line
      // to stderr (shown in the transcript, not injected into model context) so a
      // degraded run is visible without nagging on every write.
      if (plan.reason === "no-vale") {
        console.error("lint-doc-prose: vale not found on PATH — prose-lint skipped (advisory).");
      } else if (plan.reason === "no-config") {
        console.error("lint-doc-prose: no Vale config found — prose-lint skipped (advisory).");
      }
      process.exit(0);
    }

    // Vale exits non-zero when it finds alerts; that is not a hook error. Findings
    // go to stdout in line format; config/sync errors go to stderr. Reading only
    // stdout means an unsynced package (no `vale sync` yet) degrades to silence
    // rather than injecting Vale's error text as if it were prose findings.
    const proc = Bun.spawnSync([valePath!, "--config", plan.config, "--output=line", file!]);
    const findings = proc.stdout.toString().trim();
    if (findings === "") process.exit(0); // clean, or a non-finding Vale error: stay silent

    console.log(
      JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "PostToolUse",
          additionalContext: buildContext(file!, findings),
        },
      }),
    );
  } catch (err) {
    // Advisory hook: any error (malformed stdin, our own bug, a broken spawn) is a
    // silent no-op. A prose linter must never break a document write.
    console.error(`lint-doc-prose: hook error, skipping: ${String(err)}`);
  }
  process.exit(0);
}
