#!/bin/sh
# PostToolUse hook (matcher: Bash) — WARN-only, never blocks.
#
# WHY THIS EXISTS
# Long sessions are the single largest cost multiplier: usage telemetry showed
# 65% of a day's burn came from turns at >150k context, and 92% from
# subagent-heavy waves. The cheapest fix is to CLEAR between waves. The reason
# we don't is fear: clearing feels like losing the thread.
#
# A hook cannot run /clear (that is a user action, and correctly so). What it
# CAN do is make the clear free — by writing down, deterministically, everything
# a fresh session needs to pick the wave back up. Then the operator's decision
# is a keystroke, not a judgment call.
#
# WHAT IT WRITES
# .claude/wave-state.md — a GENERATED view (same class as docs/backlog.md: never
# hand-edited, regenerated from repo state). It carries the session-local facts
# that docs/STATE.md deliberately does not: what merged just now, which PRs are
# open and where they sit in the review loop, which ceremonies are overdue.
# docs/STATE.md remains the SSOT for project status; this file is the wave's
# working set, and it is disposable.
#
# It also checks whether STATE.md's ## NOW block is STALE relative to the merge
# that just landed, because clearing on top of a stale handoff is how a session
# loses the thread for real.
#
# Fires only on `gh pr merge`. Every other Bash call is a silent no-op.
# No mutation of tracked files, no network beyond the gh queries below, exit 0
# always (a broken hook must never block a merge).

set -eu

payload="$(cat)"

case "$payload" in
  *"gh pr merge"*) ;;
  *) exit 0 ;;
esac

cd "${CLAUDE_PROJECT_DIR:-.}" || exit 0

OUT=".claude/wave-state.md"

# Everything below is best-effort: a failed query degrades to a blank section
# rather than a failed hook. `|| true` on each, and never `set -e` past here.
set +e

recent=$(git log --oneline -8 2>/dev/null)
openprs=$(gh pr list --state open --json number,title,reviewDecision,mergeable \
  --jq '.[] | "- #\(.number) \(.title) [review: \(.reviewDecision // "none")] [\(.mergeable)]"' 2>/dev/null)
p1s=$(gh issue list --state open --label "priority:P1" --limit 8 --json number,title \
  --jq '.[] | "- #\(.number) \(.title)"' 2>/dev/null)
head_sha=$(git rev-parse --short HEAD 2>/dev/null)

# Is the STATE ## NOW block older than the code it is supposed to describe?
# Compare last-commit dates. A NOW block older than the newest merge is stale by
# definition -- that is the doc-freshness gate, expressed as a number.
state_epoch=$(git log -1 --format=%ct -- docs/STATE.md 2>/dev/null)
head_epoch=$(git log -1 --format=%ct 2>/dev/null)
stale="unknown"
if [ -n "$state_epoch" ] && [ -n "$head_epoch" ]; then
  if [ "$state_epoch" -lt "$head_epoch" ]; then stale="STALE"; else stale="current"; fi
fi

{
  echo "# Wave state (GENERATED — do not hand-edit)"
  echo
  echo "Regenerated by .claude/hooks/wave-close-handoff.sh on every \`gh pr merge\`."
  echo "Disposable working set for the CURRENT wave. Project status lives in docs/STATE.md (SSOT)."
  echo
  echo "HEAD: \`$head_sha\` · STATE.md ## NOW: **$stale**"
  echo
  echo "## Open PRs (where the review loop stands)"
  echo
  if [ -n "$openprs" ]; then echo "$openprs"; else echo "_none — the wave is closed._"; fi
  echo
  echo "## Open P1"
  echo
  if [ -n "$p1s" ]; then echo "$p1s"; else echo "_none._"; fi
  echo
  echo "## Recent commits"
  echo
  echo '```'
  echo "$recent"
  echo '```'
} > "$OUT" 2>/dev/null

set -e

echo "REMINDER (post-merge doc-freshness gate): a PR merge just landed."
echo "-> Refresh docs/STATE.md '## NOW' now (including in-flight work)."
echo "-> If a milestone cluster closed, update docs/milestones.md and republish the milestone-tracker Artifact."
echo "-> Dispatch the doc-steward pass BEFORE the next batch (see docs/wiki/team-structure.md)."
echo
echo "WAVE HANDOFF: .claude/wave-state.md regenerated (open PRs, open P1, recent commits)."

if [ "$stale" = "STALE" ]; then
  echo "STATE.md '## NOW' is OLDER than the merge that just landed. Refresh it BEFORE clearing —"
  echo "clearing on top of a stale handoff is how a session actually loses the thread."
else
  echo "STATE.md '## NOW' is current. If this wave is finished and no agents are running,"
  echo "a /clear costs nothing: docs/STATE.md + .claude/wave-state.md + the open issues carry it."
  echo "Long context is the largest cost multiplier we have (65% of burn came from >150k-context turns)."
fi

exit 0
