#!/usr/bin/env python3
"""Regenerate docs/backlog.md from the repo's GitHub Issues.

The GitHub Issues in this repo ARE the backlog source of truth (repo-owned).
This renders a versioned, in-git VIEW of them so the backlog is portable and
lives in git history, not in an account-hosted Projects board. The doc-steward
re-runs this after a merge cluster (see docs/wiki/working-agreements.md).

Usage:  python3 scripts/gen-backlog.py   (needs `gh` authenticated)
Groups open issues by epic label; `[P]` = parked; size from the size:* label.
"""
import json, os, subprocess

EPIC_ORDER = ["epic:improv-mode", "epic:pilot-tuning", "epic:observability",
              "epic:tech-debt", "epic:fleet", "epic:process"]
EPIC_NAME = {"epic:improv-mode": "Improv mode", "epic:pilot-tuning": "Pilot tuning",
             "epic:observability": "Observability", "epic:tech-debt": "Tech debt",
             "epic:fleet": "Fleet (parked)", "epic:process": "Process"}


def labels(it):
    return {l["name"] for l in it["labels"]}


def size(it):
    for s in ("size:S", "size:M", "size:L", "size:XL"):
        if s in labels(it):
            return s.split(":")[1]
    return ""


def epic(it):
    for e in EPIC_ORDER:
        if e in labels(it):
            return e
    return "epic:process"


def repo_root():
    # The worktree we will commit from, resolved from CWD — NOT a fixed path or
    # the git common-dir, both of which point at the MAIN checkout from a linked
    # worktree and would leak the generated file outside the steward's branch
    # (#321). A relative "docs/backlog.md" trusts CWD; anchoring to the toplevel
    # is correct even when the script is invoked from a subdirectory.
    return subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True, check=True).stdout.strip()


def main():
    root = repo_root()
    raw = subprocess.run(
        ["gh", "issue", "list", "--state", "all", "--limit", "300",
         "--json", "number,title,labels,state"],
        capture_output=True, text=True, check=True).stdout
    issues = json.loads(raw)
    open_by_epic = {e: [] for e in EPIC_ORDER}
    done = []
    for it in issues:
        (done if it["state"] == "CLOSED" else open_by_epic[epic(it)]).append(it)

    n_open = sum(len(v) for v in open_by_epic.values())
    out = ["# Backlog\n",
           "> **Generated file — do not hand-edit.** The GitHub Issues in this "
           "repo are the source of truth for the backlog; this is a versioned, "
           "in-git VIEW of them, regenerated by `scripts/gen-backlog.py` (the "
           "doc-steward runs it after a merge cluster — see "
           "`docs/wiki/working-agreements.md`). It lives in the repo so the "
           "backlog is versioned and portable, not account-hosted. `[P]` = "
           "parked; size is S/M/L/XL.\n",
           f"_Regenerated from {n_open} open issues._\n"]
    for e in EPIC_ORDER:
        its = sorted(open_by_epic[e], key=lambda x: x["number"])
        if not its:
            continue
        out.append(f"\n## {EPIC_NAME[e]}\n")
        for it in its:
            p = " `[P]`" if "parked" in labels(it) else ""
            sz = f" `{size(it)}`" if size(it) else ""
            out.append(f"- #{it['number']}{sz}{p} — {it['title']}")
    if done:
        out.append("\n## Recently done (closed)\n")
        for it in sorted(done, key=lambda x: -x["number"])[:20]:
            out.append(f"- ~~#{it['number']} — {it['title']}~~")
    out_path = os.path.join(root, "docs", "backlog.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    # Absolute path so steward-prep can confirm the write landed inside the tree
    # it will commit from (#321), not just that a file was written somewhere.
    print(f"wrote {out_path} ({n_open} open issues)")


if __name__ == "__main__":
    main()
